"""add premium column

Revision ID: 24e558427cc3
Revises: 9e95bde12042
Create Date: 2021-02-18 15:56:32.446492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24e558427cc3'
down_revision = '9e95bde12042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('premium', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price', 'premium')
    # ### end Alembic commands ###
