"""prices table

Revision ID: 9e95bde12042
Revises: 7aac13e67da9
Create Date: 2021-02-18 12:08:30.370750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e95bde12042'
down_revision = '7aac13e67da9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instock', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_timestamp'), 'price', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_timestamp'), table_name='price')
    op.drop_table('price')
    # ### end Alembic commands ###
